// src/components/Header/Header.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Link } from 'react-router-dom';
import './Header.scss';

const LOGO_URL: string = 'https://zongyuan.oss-cn-shenzhen.aliyuncs.com/ning-ui-blog/1543199721357.png'

interface Props {
    nav_active_item: string;
    user_name: string;
    logOut: () => void;
};

class Header extends React.Component<Props> {
    constructor(props) {
        super(props)
    }

    render() {
        return (
            <header>
                <nav className="flex-center-box">
                    <Link to="/index/home" replace>
                        <img className="logo" src={LOGO_URL} alt="logo"/>
                    </Link>
                    <ul className="flex-box flex-1">
                        <li className={this.props.nav_active_item.indexOf('home') > -1 ? 'active' : ''}>
                            <Link to="/index/home" replace><i className="ning-icon icon-home"></i>Home</Link>
                        </li>
                        <li className={this.props.nav_active_item.indexOf('ning-ui') > -1 ? 'active' : ''}>
                            <Link to='/index/ning-ui/text' replace><i className="ning-icon icon-ning"></i>ning-ui</Link>
                        </li>
                        <li className={this.props.nav_active_item.indexOf('article-list') > -1 ? 'active' : ''}>
                            <Link to="/index/article-list" replace><i className="ning-icon icon-article"></i>ArticleList</Link>
                        </li>
                        <li className={this.props.nav_active_item.indexOf('time-progress') > -1 ? 'active' : ''}>
                            <Link to='/time-progress-bar' replace><i className="ning-icon icon-time"></i>TimeProgress</Link>
                        </li>
                        { this.props.user_name &&
                            <li>
                                <a href="/admin.html" target="_blank"><i className="ning-icon icon-admin"></i>Admin</a>
                            </li>
                        }
                        <li className="flex-1 flex-end sign-box">
                            {
                                this.props.user_name ?
                                (
                                    <span className="flex-center-box">
                                        <Link to="/profile">Hello，{this.props.user_name}</Link>
                                        <span className="flex-center-box" id="log_out_btn" onClick={() => this.props.logOut()}><i className="ning-icon icon-log-out"></i></span>
                                    </span>
                                ) :
                                (
                                    <span>
                                        <Link to="/login"><i className="ning-icon icon-sign-in"></i>Sign-in</Link>
                                    </span>
                                )
                            }
                        </li>
                    </ul>
                </nav>
            </header>
        )
    }
}

export default Header;

// admin/src/components/header.vue
<template>
    <header>
        <nav class="flex-center-box">
            <ul class="flex-center-box flex-1">
                <li>
                    <a href="#/index/home"  class="flex-center-box">
                        <img class="logo" :src="LOGO_URL" alt="logo"/>
                    </a>
                </li>
                <li>
                    <a href="/index.html/#/index/home" target="_blank">Index</a>
                </li>
                <li class="flex-1 flex-end sign-box"  v-if="user_name">
                    <a href="#/about">Hello，{{ user_name }}</a>
                    <span class="flex-center-box" id="log_out_btn" @click="logOut()"><i class="ning-icon icon-log-out"></i></span>
                </li>
            </ul>
        </nav>
    </header>
</template>
<script>
    import axios from 'axios';
    import notify from '../assets/ning-ui/js/notify'
    export default {
        name: 'header',
        data () {
            return {
                LOGO_URL: 'https://zongyuan.oss-cn-shenzhen.aliyuncs.com/ning-ui-blog/1543199721357.png',
                user_name: null,
            }
        },
        mounted: function() {
            this.isSignIn()
        },
        methods: {
            isSignIn() {
                let self = this;
                axios.get('/api/isSignIn')
                    .then(function(response) {
                        let res = response.data;
                        if (res.status === 200) {
                            notify.success(res.message);
                            self.user_name = res.data;
                        } else {
                            location.href = '/blog/login'
                        }
                    })
                    .catch(function(error) {
                        console.log(error);
                    });
            },
            logOut() {
                let self = this;
                axios.post('/api/logOut')
                    .then(function(response) {
                        let res = response.data;
                        if (res.status === 200) {
                            notify.success(res.message);
                            location.href = '/index.html#/index/home'
                        }
                    })
                    .catch(function(error) {
                        console.log(error);
                    });
            }
        }
    }
</script>

<style lang="scss">
header{
    text-align: center;
    box-shadow: 0 2px 16px 0 rgba(223, 225, 230, 0.5);
    background: #fff;
    font-weight: bold;
    nav{
        width: 1200px;
        margin: auto;
        li{
            &.active a{
                color: $blue;
                font-weight: bold;
            }
            a{
                line-height: 60px;
                padding: 0 $md;
            }
        }
        .logo{
            width: 40px;
            height: 40px;
            margin: 0 20px;
        }
        .sign-box{
            padding-right: 0;
            a,
            #log_out_btn{
                padding: 0 $sm;
                font-size: 12px;
                color: $gray;
                cursor: pointer;
                transition: all .25s;
                &:hover{
                    color: $blue;
                }
            }
        }
    }
}
</style>
